import type { Metadata } from 'next'
import { Source_Sans_3 } from 'next/font/google'
import Header from '../components/layout/header/header'
import './globals.css'
import Footer from '../components/layout/footer'

const sourceSans = Source_Sans_3({
    subsets: ['latin'],
    variable: '--font-sourceSans'
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="hu">
            <body className={`${sourceSans.variable} font-sans leading-[1.8] tracking-wide text-darkgray`}>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    )
}
